apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: grpccalc
  name: grpccalc
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  selector:
    io.kompose.service: grpccalc
status:
  loadBalancer: {}
