#!/bin/bash

vegeta attack -duration=60s -targets=targets -rate 17000 | tee results.bin | vegeta report

vegeta report -type=json results.bin > metrics.json && \
cat results.bin | vegeta plot > plot.html && \
cat results.bin | vegeta report -type="hist[0,100ms,200ms,300ms]" && \
brave-browser plot.html

exit 0
